# Generated by Django 5.0.6 on 2024-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_venues_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='amenities',
            field=models.ManyToManyField(to='Booking.amenity'),
        ),
    ]
