# Generated by Django 5.0.6 on 2024-06-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_professional_professionalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
