# Generated by Django 5.0.6 on 2024-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_professional_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
