# Generated by Django 5.0.6 on 2024-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_alter_booking_professional_alter_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
