# Generated by Django 5.0.6 on 2024-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_professional_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prof_images/'),
        ),
    ]
